name: "X-Developer Analysis Action"
description: "Connects GitHub and X-Developer service."
author: "Chen Jiaxing"
branding:
  icon: "code"
  color: "blue"
inputs:
  APPID:
    description: "Your X-Developer APPID"
    required: true
    default: ${{ secrets.APPID }}
  APPKEY:
    description: "Your X-Developer APPKEY"
    required: true
    default: ${{ secrets.APPKEY }}
  TEAMID:
    description: "Your X-Developer TEAMID"
    required: true
    default: ${{ secrets.TEAMID }}
  Master:
    description: "Mark of master repository"
    default: False
    required: false
  Force:
    description: "Force analysis"
    default: False
    required: false
outputs:
  response:
    description: "The massage of X-Developer service response"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.APPID }}
    - ${{ inputs.APPKEY }}
    - ${{ inputs.TEAMID }}
    - ${{ inputs.Master }}
    - ${{ inputs.Force }}
