name: "X-Developer Analysis Action"
description: "Connects GitHub and X-Developer service."
author: "Chen Jiaxing"
branding:
  icon: "code"
  color: "blue"
inputs:
  APPID:
    description: "APPID of X-Developer account"
    required: true
  APPKEY:
    description: "APPKEY of X-Developer account"
    required: true
  TEAMID:
    description: "TEAMID of the team created"
    required: true
  Master:
    description: "Mark of master repository"
    default: False
    required: false
  Force:
    description: "Force analysis"
    default: False
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.APPID }}
    - ${{ inputs.APPKEY }}
    - ${{ inputs.TEAMID }}
    - ${{ inputs.Master }}
    - ${{ inputs.Force }}
