on: [push]

jobs:
  analysis:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: X-Developer analysis
      uses: ./
      with:
        APPID: ${{ secrets.APPID }}
        APPKEY: ${{ secrets.APPKEY }}
        TEAMID: ${{ secrets.TEAMID }}
        Master: True
        Force: True
